version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "8889:80"

  omeka:
    restart: always
    depends_on:
      - db
    build: ./
    ports:
      - "8888:80"
